on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: run tests
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run linters
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29

  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: go test -v -covermode count ./...

  coverage:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      
    - name: Install Go
      if: success()
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x

    - name: Install coverage badge tool
      run: go get github.com/jpoles1/gopherbadger
      
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Calc coverage
      run: |
        gopherbadger -covercmd="go test -coverprofile cover.out -coverpkg ./... ./... && go tool cover -func=cover.out"

    - name: Upload badge
      uses: zdurham/s3-upload-github-action@master
      with:
         args: --acl public-read
      env:
        FILE: ./coverage_badge.png
        S3_BUCKET: ${{ secrets.AWS_BUCKET }}
        S3_KEY: coverage_badge.png
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
