on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: quality-assurance
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      
    - name: Install Go
      if: success()
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Kingfish
      run: |
        go build ./cmd/kingfish/main.go

    - name: Run unit tests
      run: |
        go test -race -coverprofile coverage-unit.txt -covermode atomic ./...

    - name: Run integration tests
      run: |
        go test -race -coverprofile coverage-integration.txt -coverpkg ./... -covermode atomic ./...

    - name: Merge coverages
      run: |
        go get github.com/wadey/gocovmerge && gocovmerge coverage-unit.txt coverage-integration.txt

    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt
        flags: unittests
        name: codecov-umbrella
        token: ${{ secrets.CODECOV_TOKEN }}